# "A",           // a
# "B",           // b
# "C",           // c
# "D",           // d
# "E",           // e
# "F",           // f
# "G",           // g
# "H",           // h
# "I",           // i
# "J",           // j
# "K",           // k
# "L",           // l
# "M",           // m
# "N",           // n
# "O",           // o
# "P",           // p
# "Q",           // q
# "R",           // r
# "S",           // s
# "T",           // t
# "U",           // u
# "V",           // v
# "W",           // w
# "X",           // x
# "Y",           // y
# "Z",           // z
# "1",           // 1!
# "2",           // 2@
# "3",           // 3#
# "4",           // 4$
# "5",           // 5%
# "6",           // 6^
# "7",           // 7&
# "8",           // 8*
# "9",           // 9(
# "0",           // 0)
# "Enter",       // Enter
# "Esc",         // Escape
# "BS",          // Backspace
# "Tab",         // Tab
# "Space",       // Space
# "Minus",       // -_
# "Equal",       // =+
# "O_SBracket",  // [{
# "C_SBracket",  // ]}
# "Backslash",   // \|
# "Colon",       // ;:
# "Apostrophe",  // '"
# "Backquote",   // `~
# "Comma",       // ,<
# "Period",      // .>
# "Slash",       // /?
# "CapsLock",    // Caps Lock
# "F1",          // F1
# "F2",          // F2
# "F3",          // F3
# "F4",          // F4
# "F5",          // F5
# "F6",          // F6
# "F7",          // F7
# "F8",          // F8
# "F9",          // F9
# "F10",         // F10
# "F11",         // F11
# "F12",         // F12
# "PrintScreen", // Print Screen
# "ScrollLock",  // Scroll Lock
# "Pause",       // Pause
# "Ins",         // Insert
# "Home",        // Home
# "PageUp",      // Page Up
# "Del",         // Delete
# "End",         // End
# "PageDown",    // Page Down
# "Right",       // Right
# "Left",        // Left
# "Down",        // Down
# "Up",          // Up
# "NumLock",     // Num Lock
# "Katakana",    // カタカナ ひらがな
# "Yen",         // ￥|
# "Henkan",      // 変換
# "Muhenkan",    // 無変換
# "L_Control",   // Left Control
# "L_Shift",     // Left Shift
# "L_Alt",       // Left Alt
# "L_Gui",       // Left GUI
# "R_Control",   // Right Control
# "R_Shift",     // Right Shift
# "R_Alt",       // Right Alt
# "R_Gui",       // Right GUI
# "Upper",
# "Null"

[layout1]
	normal = [
		["Q",    "W",    "E",      "R",    "T",       "Y",    "U",    "I",     "O",      "P"],
		["A",    "S",    "D",      "F",    "G",       "H",    "J",    "K",     "L",      "Colon"],
		["Z",    "X",    "C",      "V",    "B",       "N",    "M",    "Comma", "Period", "Slash"],
		["Null", "LNPH", "LAYOUT", "Null", "L_Shift", "Null", "Left", "Down",  "Up",     "Right"]
	]
	upper = [
		["1",    "2",         "3",      "4",     "5",       "6",    "7",          "8",     "9",          "0"],
		["Q",    "W",         "Null",   "L_Gui", "G",       "Null", "Minus",      "Equal", "O_SBracket", "Apostrophe"],
		["Null", "R_Control", "Null",   "Null",  "Null",    "Null", "C_SBracket", "Null",  "Null",       "Yen"],
		["Null", "LNPH",      "LAYOUT", "Null",  "L_Shift", "Null", "Null",       "Null",  "Null",       "Backquote"]
	]
	stick = [
		["BS", "Tab", "Upper", "CapsLock"],
		["Esc", "Henkan", "R_Alt", "Space"]
	]

[layout2]
	normal = [
		["Apostrophe", "Comma", "O",      "U",    "Y",       "F",    "G",    "C",    "R",  "L"],
		["P",          "I",     "E",      "A",    "Period",  "D",    "S",    "T",    "H",  "Z"],
		["J",          "Q",     "Colon",  "K",    "X",       "B",    "M",    "W",    "N",  "V"],
		["Null",       "LNPH",  "LAYOUT", "Null", "L_Shift", "Null", "Left", "Down", "Up", "Right"]
	]
	upper = [
		["1",          "2",        "3",      "4",     "5",       "6",    "7",          "8",          "9",     "0"],
		["Apostrophe", "Comma",    "Null",   "L_Gui", "Period",  "Null", "O_SBracket", "C_SBracket", "Slash", "Minus"],
		["Null",       "CapsLock", "Null",   "Null",  "Null",    "Null", "Equal",      "Null",       "Null",  "Backslash"],
		["Null",       "LNPH",     "LAYOUT", "Null",  "L_Shift", "Null", "Null",       "Null",       "Null",  "Backquote"]
	]
	stick = [
		["BS", "Tab", "Upper", "L_Control"],
		["Esc", "Space", "R_Alt", "Enter"]
	]

