# "A",           // a
# "B",           // b
# "C",           // c
# "D",           // d
# "E",           // e
# "F",           // f
# "G",           // g
# "H",           // h
# "I",           // i
# "J",           // j
# "K",           // k
# "L",           // l
# "M",           // m
# "N",           // n
# "O",           // o
# "P",           // p
# "Q",           // q
# "R",           // r
# "S",           // s
# "T",           // t
# "U",           // u
# "V",           // v
# "W",           // w
# "X",           // x
# "Y",           // y
# "Z",           // z
# "1",           // 1!
# "2",           // 2@
# "3",           // 3#
# "4",           // 4$
# "5",           // 5%
# "6",           // 6^
# "7",           // 7&
# "8",           // 8*
# "9",           // 9(
# "0",           // 0)
# "Enter",       // Enter
# "Esc",         // Escape
# "BS",          // Backspace
# "Tab",         // Tab
# "Space",       // Space
# "Minus",       // -_
# "Equal",       // =+
# "O_SBracket",  // [{
# "C_SBracket",  // ]}
# "Backslash",   // \|
# "Colon",       // ;:
# "Apostrophe",  // '"
# "Backquote",   // `~
# "Comma",       // ,<
# "Period",      // .>
# "Slash",       // /?
# "CapsLock",    // Caps Lock
# "F1",          // F1
# "F2",          // F2
# "F3",          // F3
# "F4",          // F4
# "F5",          // F5
# "F6",          // F6
# "F7",          // F7
# "F8",          // F8
# "F9",          // F9
# "F10",         // F10
# "F11",         // F11
# "F12",         // F12
# "PrintScreen", // Print Screen
# "ScrollLock",  // Scroll Lock
# "Pause",       // Pause
# "Ins",         // Insert
# "Home",        // Home
# "PageUp",      // Page Up
# "Del",         // Delete
# "End",         // End
# "PageDown",    // Page Down
# "Right",       // Right
# "Left",        // Left
# "Down",        // Down
# "Up",          // Up
# "NumLock",     // Num Lock
# "Katakana",    // カタカナ ひらがな
# "Yen",         // ￥|
# "Henkan",      // 変換
# "Muhenkan",    // 無変換
# "L_Control",   // Left Control
# "L_Shift",     // Left Shift
# "L_Alt",       // Left Alt
# "L_Gui",       // Left GUI
# "R_Control",   // Right Control
# "R_Shift",     // Right Shift
# "R_Alt",       // Right Alt
# "R_Gui",       // Right GUI
# "Null"

# ["keycode", "modifiers"]
# modifiers = RG,RA,RS,RC,LG,LA,LS,LC

[layout1]
	normal = [
		[["Esc", "00000000"],  ["1", "00000000"],    ["2", "00000000"],      ["3", "00000000"],    ["4", "00000000"],  ["5", "00000000"],   ["6", "00000000"],     ["7", "00000000"],     ["8", "00000000"],        ["9", "00000000"],      ["0", "00000000"],     ["Minus", "00000000"],      ["Equal", "00000000"]],
		[["Tab", "00000000"],  ["Q", "00000000"],    ["W", "00000000"],      ["E", "00000000"],    ["R", "00000000"],  ["T", "00000000"],   ["Y", "00000000"],     ["U", "00000000"],     ["V", "00000000"],        ["O", "00000000"],      ["P", "00000000"],     ["O_SBracket", "00000000"], ["C_SBracket", "00000000"]],
		[["Null", "00000001"], ["A", "00000000"],    ["S", "00000000"],      ["D", "00000000"],    ["F", "00000000"],  ["G", "00000000"],   ["H", "00000000"],     ["J", "00000000"],     ["K", "00000000"],        ["L", "00000000"],      ["Colon", "00000000"], ["Apostrophe", "00000000"], ["Yen", "00000000"]],
		[["Null", "00000010"], ["Z", "00000000"],    ["X", "00000000"],      ["C", "00000000"],    ["I", "00000000"],  ["B", "00000000"],   ["N", "00000000"],     ["M", "00000000"],     ["Comma", "00000000"],    ["Period", "00000000"], ["Slash", "00000000"], ["Null", "00100000"],       ["Backquote", "00000000"]],
		[["Null", "00001000"], ["LNPH", "00000000"], ["LAYOUT", "00000000"], ["Null", "00000100"], ["BS", "00000000"], ["Del", "00000000"], ["Enter", "00000000"], ["Space", "00000000"], ["CapsLock", "00000000"], ["Left", "00000000"],   ["Down", "00000000"],  ["Up", "00000000"],         ["Right", "00000000"]]
	]

[layout2]
	normal = [
		[["Esc", "00000000"],  ["1", "00000000"],          ["2", "00000000"],      ["3", "00000000"],     ["4", "00000000"],  ["5", "00000000"],      ["6", "00000000"],     ["7", "00000000"],     ["8", "00000000"],        ["9", "00000000"],    ["0", "00000000"],    ["O_SBracket", "00000000"], ["C_SBracket", "00000000"]],
		[["Tab", "00000000"],  ["Apostrophe", "00000000"], ["Comma", "00000000"],  ["O", "00000000"],     ["U", "00000000"],  ["Y", "00000000"],      ["F", "00000000"],     ["G", "00000000"],     ["C", "00000000"],        ["R", "00000000"],    ["L", "00000000"],    ["Slash", "00000000"],      ["Equal", "00000000"]],
		[["Null", "00000001"], ["P", "00000000"],          ["I", "00000000"],      ["E", "00000000"],     ["A", "00000000"],  ["Period", "00000000"], ["D", "00000000"],     ["S", "00000000"],     ["T", "00000000"],        ["H", "00000000"],    ["Z", "00000000"],    ["Minus", "00000000"],      ["Backslash", "00000000"]],
		[["Null", "00000010"], ["J", "00000000"],          ["Q", "00000000"],      ["Colon", "00000000"], ["K", "00000000"],  ["X", "00000000"],      ["B", "00000000"],     ["M", "00000000"],     ["W", "00000000"],        ["N", "00000000"],    ["V", "00000000"],    ["Null", "00100000"],       ["Backquote", "00000000"]],
		[["Null", "00001000"], ["LNPH", "00000000"],       ["LAYOUT", "00000000"], ["Null", "00000100"],  ["BS", "00000000"], ["Del", "00000000"],    ["Enter", "00000000"], ["Space", "00000000"], ["CapsLock", "00000000"], ["Left", "00000000"], ["Down", "00000000"], ["Up", "00000000"],         ["Right", "00000000"]]
	]
